# Generated by Django 3.0.4 on 2020-10-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('计算机科学与技术学院', '计算机科学与技术学院'), ('电气与自动化学院', '电气与自动化学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院')], max_length=100, null=True, verbose_name='学院名称')),
                ('num', models.CharField(default=0, max_length=2, verbose_name='所在楼号')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='dormitory',
            fields=[
                ('dno', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='寝室号')),
                ('num', models.CharField(default=0, max_length=2, verbose_name='所在楼号')),
                ('content', models.CharField(default=None, max_length=40, verbose_name='卫生检查情况')),
                ('people', models.IntegerField(default=4, verbose_name='宿舍人数')),
            ],
            options={
                'verbose_name': '寝室',
                'verbose_name_plural': '寝室',
                'db_table': 'dormitory',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sclass', models.CharField(default=0, max_length=2, verbose_name='年级')),
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('spass', models.CharField(default='123456', max_length=40, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('dno', models.CharField(default=0, max_length=3, verbose_name='寝室号')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('roles', models.ManyToManyField(to='rbac.Role')),
                ('sdept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.department', verbose_name='学院')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
