# Generated by Django 3.0.4 on 2020-10-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20201002_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='sclass',
            field=models.CharField(default=0, max_length=2, verbose_name='所属年级'),
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('sclass', models.CharField(default=0, max_length=2, verbose_name='年级')),
                ('tno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('spass', models.CharField(default='123456', max_length=40, verbose_name='密码')),
                ('roles', models.ManyToManyField(to='rbac.Role')),
            ],
            options={
                'verbose_name': '教工',
                'verbose_name_plural': '教工',
                'db_table': 'teacher',
            },
        ),
    ]
