# Generated by Django 3.0.4 on 2020-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20201005_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电话号码'),
        ),
    ]
